### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by gearskill** [swag-engineering/simbind-cli#13]
Hello,
I get the following errror when I try to convert my .slx Model:
pycparser.plyparser.parseerror: /tmp/tmpk6mkn1s3/ne_std.h:12:15: before(

It seems like the package can't read some C code.

Do you have any ideas how I can fix this?
Thank you very much in advance!

**Comment by antonrak** [comment]
Hello @gearskill,
sorry for late reply!
Would it be comfortable for you to send your slx to contact@swagengineering.io? I will try to reproduce the problem.

**Comment by gearskill** [comment]
Hello,
I'm sorry but I can't send you an email to the contact@swagengineering.io, because the domain swagengineering.io couldn't be found.

**Comment by antonrak** [comment]
@gearskill
oooopsie, contact@swag-engineering.io

**Comment by antonrak** [comment]
After reviewing the issue it appears that pycparser is not able to parse Simscape generated headers. A for now I see two solutions:
- Override [CParser](https://github.com/eliben/pycparser/blob/main/pycparser/c_parser.py)
- switch to [libclang](https://libclang.readthedocs.io/en/latest/) for C code parsing

Unfortunately,  I do not have enough free time at the moment to implement any of above mentioned solutions

**Comment by antonrak** [comment]
I have took time to review issue again and found solution.
The problem itself was related to the fact that Simulink(+Simscape) generated GNU gcc specific code with [__attribute​​__](https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html), it was just not comprehensive from the start due to obfuscated code generated for Simscape. [Here](https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/) pycparser's author explains how to truncate GNU-specific definitions.

I have added to Simbind --preprocessor-def argument to pass these definitions to preprocessor. I have also added --matlab-include argument for eliminating the need to compose Simulink model into single _.slx_, since it's not always easily possible.

The updated version of Simbind was rolled out to [PyPI](https://pypi.org/project/simbind/).
